"use client";

import { useState } from "react";
import { Dialog, Tabs } from "radix-ui";
import { ArrowLeft, ArrowRight, Camera, CheckCheck, Download, FileText, Fingerprint, Play, ShieldCheck, Sparkles, X } from "lucide-react";
import { exportReport, type Report } from "@/lib/assessment";
import { recordedProviderLabel } from "@/lib/ai-metadata";
import { isSyntheticRecord } from "@/lib/atlas";
import { labDecisionBrief, labRecordSummary } from "@/lib/evidence-lab";
import { downloadFile, findingLabels, observationQuality } from "@/lib/field";
import { displayEvidenceTime } from "@/lib/references";
import { nextPresentationStage, presentationBrief, presentationLabels, presentationStages, presentationWorkflow, type PresentationStage } from "@/lib/presentation-brief";
import { EvidenceImage } from "./field-studio";

export function DecisionPresentation({ report }: { report: Report }) {
  const [open, setOpen] = useState(false);
  const [stage, setStage] = useState<PresentationStage>("evidence");
  const [mediaIndex, setMediaIndex] = useState(0);
  const [availability, setAvailability] = useState<{ id: string; available: boolean } | null>(null);
  if (isSyntheticRecord(report)) return null;
  const media = report.field?.media[mediaIndex] ?? report.field?.media[0];
  const ref = report.field?.reference;
  const summary = labRecordSummary(report);
  const quality = observationQuality(report);
  const review = labDecisionBrief(report);
  const currentReview = review.latestReview;
  const workflow = presentationWorkflow(report);
  const index = presentationStages.indexOf(stage);
  return <Dialog.Root open={open} onOpenChange={(next) => { setOpen(next); if (next) { setStage("evidence"); setMediaIndex(0); } }}>
    <Dialog.Trigger asChild><button type="button" className="btn presentation-trigger"><Play size={16} /> Present this evidence <ArrowRight size={16} /></button></Dialog.Trigger>
    <Dialog.Portal><Dialog.Overlay className="dp-overlay" /><Dialog.Content className="dp-dialog">
      <header className="dp-header"><div><p className="dp-eyebrow">AQUALENS / EVIDENCE STORY</p><Dialog.Title>{report.original.site || "Recorded observation"}</Dialog.Title><Dialog.Description>A read-only story of original evidence and retained human decisions.</Dialog.Description></div><Dialog.Close asChild><button type="button" className="dp-icon-button" aria-label="Close evidence presentation"><X size={22} /></button></Dialog.Close></header>
      <Tabs.Root className="dp-story" value={stage} onValueChange={(value) => { if (presentationStages.includes(value as PresentationStage)) setStage(value as PresentationStage); }}>
        <Tabs.List className="dp-stages" aria-label="Evidence story chapters">{presentationStages.map((key, step) => <Tabs.Trigger key={key} value={key}><span>{String(step + 1).padStart(2, "0")}</span>{presentationLabels[key]}</Tabs.Trigger>)}</Tabs.List>
        <div className="dp-layout">
          <aside className="dp-image-column"><div className="dp-frame">{media ? <EvidenceImage key={media.id} media={media} controls onAvailability={(available) => setAvailability({ id: media.id, available })} /> : <div className="dp-no-media"><Camera size={44} /><strong>No media was recorded.</strong><p>The original note remains available for review.</p></div>}<span className="dp-source-badge">{ref ? "HISTORICAL PHOTO REVIEW" : "CITIZEN FIELD EVIDENCE"}</span></div>
            {!!report.field?.media.length && <div className="dp-media-choices" role="group" aria-label="Choose recorded media">{report.field.media.map((item, step) => <button type="button" key={item.id} aria-pressed={item.id === media?.id} onClick={() => setMediaIndex(step)}>{item.kind === "video" ? "Clip" : "Photo"} {step + 1}</button>)}</div>}
            <div className="dp-source-caption"><p><Fingerprint size={14} /> {availability && availability.id === media?.id ? availability.available ? "Local media loaded" : "Media not loaded in this browser" : media ? "Loading local media…" : "Original text retained"}</p><time>{displayEvidenceTime(report.original.observedAt)}</time>{ref && <p>Photo: {ref.author} · <a href={ref.licenseUrl} target="_blank" rel="noreferrer">{ref.license}</a> · <a href={ref.sourceUrl} target="_blank" rel="noreferrer">Source & history</a></p>}<small>Image framing is display only. A photograph does not establish water safety.</small></div>
          </aside>
          <div className="dp-chapters">
            <Tabs.Content value="evidence"><p className="dp-eyebrow">01 / PRESERVE THE SOURCE</p><h2>Start with what was observed.</h2><p className="dp-intro">{ref ? "A human-authored review of a credited historical photograph." : "The citizen's original note and supplied context."}</p><blockquote className="dp-original">{report.original.note}</blockquote><div className="dp-facts"><div><span>Reported appearance</span><strong>{report.original.appearance}</strong></div><div><span>Recorded media</span><strong>{report.field?.media.length ?? 0} files</strong></div><div><span>Instrument readings</span><strong>{report.field?.measurements.length ?? 0} supplied</strong></div><div><span>Location metadata</span><strong>{report.field?.coordinates ? "Supplied · not independently verified" : "Not supplied · optional"}</strong></div></div><p className="dp-limit">Unknowns stay unknown. Historical sources are separate from current field visits.</p></Tabs.Content>
            <Tabs.Content value="assessment"><p className="dp-eyebrow">02 / MAKE CHECKS EXPLAINABLE</p><h2>A question is an invitation to clarify.</h2><p className="dp-intro">{report.assessment.mode === "ai" ? `${recordedProviderLabel(report.assessment.provider)} · ${report.assessment.model || "Model not retained"}` : "Local English rules"} · recorded method</p><div className="dp-counts"><span><strong>{summary.ruleChecks}</strong>Rule questions</span><span><strong>{summary.textAICandidates}</strong>Text AI suggestions</span><span><strong>{summary.visualAICandidates}</strong>Visual candidates</span></div><p className="dp-notice">{report.assessment.notice}</p><div className="dp-question-list">{report.assessment.issues.map((issue) => <article key={issue.id}><div><span>{issue.source === "ai" ? "AI suggestion" : "Rule check"}</span><b>{issue.decision}</b></div><h3>{issue.title}</h3>{issue.quote && <blockquote>{issue.quote}</blockquote>}<p><strong>Citizen response: </strong>{issue.answer || "No response recorded"}</p></article>)}{!report.assessment.issues.length && <p className="dp-notice">No text questions were retained. This does not establish environmental health.</p>}</div><details className="dp-rubric"><summary>Observation Quality · {quality.value}/100 evidence completeness</summary>{quality.checks.map((check) => <p key={check.label}>{check.label}<strong>{check.earned}/{check.max}</strong></p>)}<small>{quality.method} · transparent app rubric, not ecological quality or model confidence.</small></details></Tabs.Content>
            <Tabs.Content value="judgment"><p className="dp-eyebrow">03 / KEEP PEOPLE IN CONTROL</p><h2>Human decisions stay visible.</h2><div className={`dp-review-status ${review.reviewComplete ? "is-reviewed" : ""}`}><ShieldCheck size={21} /><strong>{workflow}</strong></div><p className="dp-intro">Citizen confirmation: {displayEvidenceTime(report.confirmedAt)}. Confirmation records approval, not scientific truth.</p>{currentReview ? <article className="dp-human-note"><span>Latest recorded review event · local demo reviewer</span><blockquote>{currentReview.note}</blockquote><time>{displayEvidenceTime(currentReview.at)}</time><small>{report.status !== "reviewed" ? "Current workflow is still open; an earlier review event does not close it." : "Reviewer identity is not authenticated."}</small></article> : <p className="dp-notice">No local human review event is recorded. This presentation does not approve the report.</p>}<details className="dp-rubric"><summary>Review completeness and retained limits</summary>{review.gaps.length ? review.gaps.map((gap) => <p key={gap}>{gap}</p>) : <p>No missing stages were detected by this app rubric. This is not independent verification.</p>}</details><div className="dp-judgments">{report.field?.media.flatMap((item) => item.visual?.findings.map((finding, findingIndex) => { const judgment = report.field?.dispositions.filter((entry) => entry.mediaId === item.id && entry.finding === finding.kind).at(-1); return <article key={`${item.id}-${finding.kind}-${findingIndex}`}><p><Sparkles size={14} />{findingLabels[finding.kind]}</p><span>{recordedProviderLabel(item.visual?.provider)} · {finding.confidence} uncalibrated confidence</span><strong>{judgment ? `Human: ${judgment.decision}` : "Human: awaiting judgment"}</strong>{judgment && <blockquote>{judgment.reason}</blockquote>}</article>; }) ?? [])}</div><p className="dp-limit">{summary.visualDisagreements} current visual disagreements · {summary.visualNeedsJudgment} awaiting or uncertain visual judgments. These are retained workflow counts.</p></Tabs.Content>
            <Tabs.Content value="receipt"><p className="dp-eyebrow">04 / MAKE THE HANDOFF TRACEABLE</p><h2>Evidence travels with its decisions.</h2><div className="dp-receipt-mark"><CheckCheck size={32} /><div><strong>Decision Receipt</strong><span>{workflow}</span></div></div><dl className="dp-receipt-details"><div><dt>Record ID</dt><dd>{report.id}</dd></div><div><dt>Schema</dt><dd>{report.schemaVersion} · local browser record</dd></div><div><dt>Original confirmation</dt><dd>{displayEvidenceTime(report.confirmedAt)}</dd></div><div><dt>Recorded history</dt><dd>{report.history.length} workflow events · {report.reviewHistory.length} review events</dd></div></dl><div className="dp-export-actions"><button type="button" onClick={() => downloadFile(exportReport(report), `aqualens-${report.id}.json`)}><Download size={16} /> JSON receipt</button><button type="button" onClick={() => downloadFile(presentationBrief(report), `aqualens-${report.id}-brief.md`, "text/markdown;charset=utf-8")}><FileText size={16} /> Readable brief</button></div><p className="dp-notice">These exports contain recorded text and metadata. Use Field kit for a pack with original media bytes. A hash detects changed bytes; it does not authenticate a scene or observer.</p><p className="dp-limit">No water-safety, pathogen, pollutant, species or ecological conclusion is established by this receipt.</p></Tabs.Content>
          </div>
        </div>
      </Tabs.Root>
      <footer className="dp-footer"><button type="button" disabled={index === 0} onClick={() => setStage(nextPresentationStage(stage, -1))}><ArrowLeft size={16} /> Previous</button><p aria-live="polite">{index + 1} / {presentationStages.length} · {presentationLabels[stage]}</p><button type="button" disabled={index === presentationStages.length - 1} onClick={() => setStage(nextPresentationStage(stage, 1))}>Next <ArrowRight size={16} /></button></footer>
    </Dialog.Content></Dialog.Portal>
  </Dialog.Root>;
}
