"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, Check, CheckCheck, ChartNoAxesCombined, FileCheck2, FlaskConical, Minus, SlidersHorizontal, X } from "lucide-react";
import type { Report } from "@/lib/assessment";
import { scopedRecords, recordSignals, workspaceAnalytics, workflowLabels, type EvidenceScope } from "@/lib/mission-control";
import { displayEvidenceTime } from "@/lib/references";
import { validationReportSchema } from "@/lib/validation-report";
import { RiverPortfolio, photoCity } from "./river-portfolio";

const colors = ["#e9b66b", "#a58bff", "#4bd6b0"];
const suites = [{ file: "evaluation", name: "Domain behavior" }, { file: "workspace-evaluation", name: "Source & transfer integrity" }, { file: "mission-evaluation", name: "Visual workspace logic" }, { file: "api-evaluation", name: "Mocked API contracts" }];
type Suite = { name: string; file: string; passed?: number; total?: number; generatedAt?: string; failed?: boolean };
function EngineeringValidation() {
  const [results, setResults] = useState<Suite[]>(suites);
  useEffect(() => {
    let current = true;
    Promise.all(suites.map(async (suite): Promise<Suite> => {
      try {
        const response = await fetch(`/${suite.file}.json`);
        if (!response.ok) throw new Error();
        const data = validationReportSchema.parse(await response.json());
        return { ...suite, passed: data.passed, total: data.total, generatedAt: data.generatedAt };
      } catch { return { ...suite, failed: true }; }
    })).then((data) => { if (current) setResults(data); });
    return () => { current = false; };
  }, []);
  return <section className="engineering-console"><div className="mc-panel-heading"><span><FlaskConical size={15} /> ENGINEERING VALIDATION</span><span className="mc-chip violet">AUTHORED SOFTWARE TESTS</span></div><div className="validation-cards">{results.map((suite) => <a key={suite.file} href={`/${suite.file}.json`} target="_blank" rel="noreferrer"><span>{suite.name}<ArrowUpRight size={14} /></span><strong>{suite.passed ?? "—"}<small> / {suite.total ?? "—"}</small></strong><div className="validation-meter"><i style={{ width: `${suite.total ? 100 * suite.passed! / suite.total : 0}%` }} /></div><small>{suite.total ? suite.passed === suite.total ? "All checks passed" : "Inspect failing checks" : suite.failed ? "Test report unavailable" : "Loading test report…"}</small>{suite.generatedAt && <time dateTime={suite.generatedAt}>{displayEvidenceTime(suite.generatedAt)}</time>}</a>)}</div><p className="mc-footnote">These are actual generated development-test results. They do not measure ecological accuracy, model calibration, successful live AI, or browser/device performance.</p></section>;
}
export function EvidenceInsights({ records, onOpen, onStart }: { records: Report[]; onOpen: (id: string) => void; onStart: () => void }) {
  const [diagnosticsOpen, setDiagnosticsOpen] = useState(false);
  const [city, setCity] = useState("all");
  const [scope, setScope] = useState<EvidenceScope>("all"), [status, setStatus] = useState("all"), [day, setDay] = useState("");
  const scoped = useMemo(() => scopedRecords(records, scope), [records, scope]);
  const source = useMemo(() => scoped.filter((record) => city === "all" || photoCity(record.field?.reference?.id) === city), [scoped, city]);
  const metrics = useMemo(() => workspaceAnalytics(source), [source]);
  const shown = source.filter((r) => (status === "all" || r.status === status) && (!day || (Number.isFinite(Date.parse(r.createdAt)) && new Date(r.createdAt).toISOString().slice(0, 10) === day)));
  const maxActivity = Math.max(1, ...metrics.activity.map((point) => point.count));
  const activityCounts = [metrics.ruleQuestions, metrics.aiQuestions, metrics.visualCandidates, metrics.annotations];
  const sourceMax = Math.max(1, ...activityCounts);
  const includesExamples = source.some((record) => record.demonstration);
  const visualNotesLabel = includesExamples ? "Visual notes · includes examples" : "Human visual notes";
  return <div className="insights-console"><header className="mc-page-heading"><div><p className="mc-kicker"><ChartNoAxesCombined size={14} /> WORKSPACE INTELLIGENCE</p><h1>See what the evidence contains.</h1><p>Explore collection coverage, review activity and retained sources.</p></div><label className="mc-scope-label"><SlidersHorizontal size={15} /> Evidence scope<select value={scope} onChange={(event) => { setScope(event.target.value as EvidenceScope); setCity("all"); setStatus("all"); setDay(""); }}><option value="all">All saved records</option><option value="field">Field observations</option><option value="reference">Historical photo reviews</option></select></label></header>
    <RiverPortfolio records={scoped} city={city} onCity={(id) => { setCity(id); setStatus("all"); setDay(""); }} onOpen={onOpen} />
    <div className="insight-metrics">{[{ label: "Saved records", value: metrics.total, detail: `${metrics.field} field · ${metrics.references} historical reviews`, icon: FileCheck2 }, { label: "Questions retained", value: metrics.ruleQuestions + metrics.aiQuestions, detail: `${metrics.ruleQuestions} rules · ${metrics.aiQuestions} text AI`, icon: Activity }, { label: "Visual judgments due", value: metrics.unjudgedCandidates, detail: `Of ${metrics.visualCandidates} retained AI candidates`, icon: CheckCheck }, { label: visualNotesLabel, value: metrics.annotations, detail: "Original pixels preserved", icon: ChartNoAxesCombined }].map(({ label, value, detail, icon: Icon }) => <article key={label}><div><span>{label}</span><Icon size={18} /></div><strong>{value}</strong><small>{detail}</small></article>)}</div>
    <div className="insight-grid"><section className="insight-card workflow-chart"><div className="mc-panel-heading"><span>REVIEW DISTRIBUTION</span><span className="mc-chip">{metrics.total} RECORDS</span></div><div className="workflow-donut"><svg viewBox="0 0 180 180" role="img" aria-label={`Workflow distribution of ${metrics.total} saved records`}><circle className="donut-track" cx="90" cy="90" r="68" />{metrics.statuses.map((item, index) => { const share = metrics.total ? item.count / metrics.total * 100 : 0; const start = metrics.total ? metrics.statuses.slice(0, index).reduce((sum, segment) => sum + segment.count, 0) / metrics.total * 100 : 0; return <circle key={item.status} cx="90" cy="90" r="68" pathLength="100" fill="none" stroke={colors[index]} strokeWidth="13" strokeDasharray={`${share} ${100 - share}`} strokeDashoffset={-start} transform="rotate(-90 90 90)" />; })}<text x="90" y="90" className="donut-value">{metrics.total}</text><text x="90" y="111" className="donut-label">SAVED RECORDS</text></svg></div><div className="workflow-legend">{metrics.statuses.map((item, index) => <button key={item.status} type="button" aria-pressed={status === item.status} onClick={() => setStatus(status === item.status ? "all" : item.status)}><i style={{ background: colors[index] }} /><span>{item.label}{includesExamples ? " · example" : ""}</span><b>{item.count}</b></button>)}</div><p className="mc-footnote">Select a status to filter the evidence matrix. Review status is not scientific validation.</p></section>
      <section className="insight-card coverage-chart"><div className="mc-panel-heading"><span>EVIDENCE COVERAGE</span><span className="mc-chip">RECORD METADATA</span></div><div className="coverage-bars">{metrics.coverage.map((item) => <div key={item.key}><div><span>{includesExamples && (item.key === "confirmed" || item.key === "reviewed") ? `${item.label} · examples included` : item.label}</span><b>{item.count}<small> / {item.total}</small></b></div><div className="coverage-track"><i style={{ width: `${item.total ? item.count / item.total * 100 : 0}%` }} /></div></div>)}</div><p className="mc-footnote">Counts include metadata, not verified file availability. Historical photo reviews are excluded from the coordinates denominator. Acknowledged questions can remain uncertain.</p></section>
      <section className="insight-card source-chart"><div className="mc-panel-heading"><span>RETAINED ACTIVITY</span><span className="mc-chip violet">SOURCE COUNTS</span></div>{["Local rule questions", "Text AI questions", "Visual AI candidates", visualNotesLabel].map((label, index) => <div className="source-count" key={label}><span>{label}<strong>{activityCounts[index]}</strong></span><div><i style={{ width: `${activityCounts[index] / sourceMax * 100}%`, background: ["#e9b66b", "#a58bff", "#35c9e8", "#4bd6b0"][index] }} /></div></div>)}<div className="source-explanation"><GitSourceGlyph /><p>{includesExamples ? "Initial example notes and review decisions are AI-authored demonstrations, not expert validation. Later edits retain their history." : "Each contribution keeps its source and its human decisions."} Source counts describe the workflow; they are not influence or confidence scores.</p></div></section>
      <section className="insight-card activity-chart"><div className="mc-panel-heading"><span><Activity size={15} /> SAVING ACTIVITY</span><span className="mc-chip">LAST 14 UTC DAYS</span></div><div className="activity-plot" aria-label="Daily count of record creation timestamps">{metrics.activity.map((point) => <button type="button" key={point.day} aria-pressed={day === point.day} aria-label={`${point.day}: ${point.count} records saved. Filter to this day.`} onClick={() => setDay(day === point.day ? "" : point.day)}><span className="activity-value">{point.count || ""}</span><span className="activity-bar-space"><i style={{ height: `${point.count / maxActivity * 100}%` }} /></span><time dateTime={point.day}>{point.day.slice(8)}</time><span className="activity-tooltip">{point.day} · {point.count} saved</span></button>)}</div><div className="activity-axis"><span>{metrics.activity[0].day}</span><span>Record creation dates</span><span>{metrics.activity.at(-1)!.day}</span></div><p className="mc-footnote">A historical photo’s source date is separate from when its review was created. Older saved records remain in the collection.</p></section></div>
    <section className="insight-card evidence-matrix"><div className="mc-panel-heading"><span>EVIDENCE MATRIX</span><span className="mc-chip">{shown.length} MATCHING RECORDS</span></div>{(status !== "all" || day) && <div className="matrix-filter"><span>{status !== "all" ? workflowLabels[status as Report["status"]] : "All statuses"}{day && ` · Created ${day} UTC`}</span><button type="button" onClick={() => { setStatus("all"); setDay(""); }}><X size={14} /> Clear filters</button></div>}
      {shown.length ? <div className="matrix-scroll"><table><thead><tr><th scope="col">Record / source</th>{["Note", "Media", "GPS", "Questions", "Confirmed", "Reviewed"].map((label) => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{shown.slice(0, 60).map((report) => <tr key={report.id}><th scope="row"><button type="button" onClick={() => onOpen(report.id)}>{report.original.site}<ArrowUpRight size={13} /><small>{report.field?.reference ? "Historical photo review" : "Field observation"}{report.demonstration ? " · example" : ""} · {report.original.observedAt.slice(0, 10)}</small></button></th>{recordSignals(report).map((signal) => <td key={signal.key}><span className={`matrix-cell ${!signal.applicable ? "na" : signal.present ? "present" : "missing"}`} title={`${signal.label}: ${!signal.applicable ? "not applicable" : signal.present ? "recorded" : "not recorded / pending"}`}><span className="sr-only">{!signal.applicable ? "Not applicable" : signal.present ? "Recorded" : "Not recorded or pending"}</span>{signal.applicable && signal.present ? <Check size={15} /> : <Minus size={14} />}</span></td>)}</tr>)}</tbody></table>{shown.length > 60 && <p className="mc-footnote">Showing 60 of {shown.length} records. Narrow the scope, workflow or day filter.</p>}</div> : <div className="mc-empty"><ChartNoAxesCombined size={32} /><h3>{source.length ? "No records match these filters." : "Your first saved record starts the story."}</h3><p>Coverage and activity fill in as you confirm real observations or credited photo reviews.</p><button type="button" className="mc-button accent" onClick={onStart}>Open the field kit <ArrowUpRight size={14} /></button></div>}<div className="matrix-legend"><span><i className="present" /> Recorded</span><span><i className="missing" /> Missing / pending</span><span><i className="na" /> Not applicable</span><small>Click a record to inspect its full receipt.</small></div></section>
    <details className="insights-diagnostics" open={diagnosticsOpen} onToggle={(event) => setDiagnosticsOpen(event.currentTarget.open)}><summary><FlaskConical size={16} /> Software diagnostics <span>Authored checks · separate from environmental evidence</span></summary>{diagnosticsOpen && <EngineeringValidation />}</details>
  </div>;
}
function GitSourceGlyph() { return <svg viewBox="0 0 100 50" aria-hidden="true"><path d="M 8 10 C 40 10, 35 25, 52 25 S 75 8, 92 8 M 8 40 C 40 40, 35 25, 52 25 S 75 42, 92 42 M 52 25 H 92" fill="none" stroke="currentColor" strokeWidth="1.5" />{[[8,10],[8,40],[52,25],[92,8],[92,25],[92,42]].map(([x,y]) => <circle key={`${x}-${y}`} cx={x} cy={y} r="3" fill="currentColor" />)}</svg>; }
