import { z } from "zod";

// Public historical photographs, never seeded citizen observations.
// Source metadata was checked against the Wikimedia Commons file pages.
export const archivedReferencePhotos = [
  {
    id: "mutha-river",
    title: "Mutha River, Pune",
    site: "Mutha River, Pune",
    role: "01 / A wider view",
    alt: "River with a bridge, buildings, banks and patches of vegetation visible in the water.",
    src: "/images/references/mutha-river.jpg",
    author: "Ak2431989",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mutha_River,_Pune.jpg",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    capturedDate: "2010-08-03",
    sha256: "f35a0b97e68755920de1a5df0fcc9325f4ec939fa93142d6061256ad4b9f132f",
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit.",
  },
  {
    id: "scenic-reflection",
    title: "Scenic Reflection",
    site: "Mutha River, Pune",
    role: "02 / Surface & surroundings",
    alt: "Trees and buildings reflected in the river, with vegetation and scattered objects in the foreground.",
    src: "/images/references/scenic-reflection.jpg",
    author: "Sharvarism",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Scenic_Reflection.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    capturedDate: "2023-06-06",
    sha256: "0d991a31833a907e4815c253f2d83907550b99115bfe1135d2d439385e1fe8cd",
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit.",
  },
  {
    id: "sambhaji-bank",
    title: "Sambhaji Bridge through the trees",
    site: "Mutha River, Sambhaji Bridge, Pune",
    role: "03 / The riverbank",
    alt: "Sambhaji Bridge viewed from a grassy riverbank through overhanging branches.",
    src: "/images/references/sambhaji-bank.jpg",
    author: "DesiBoy101",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sambhaji_Bridge_as_seen_through_the_trees_on_the_banks_of_Mutha_River_in_Pune.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    capturedDate: "2023-06-12",
    sha256: "518ef0b89fb2bdd1f972e21c83c2b7c01c7a9d5b35d6025582a9c3f70a782bda",
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit.",
  },
] as const;
// Active European source gallery. Old sources remain valid for existing receipts only.
export const referencePhotos = [
  { id: "mondego-coimbra", title: "Mondego · Coimbra", site: "Mondego River, Coimbra, Portugal", role: "01 / River & city",
    alt: "Wide river foreground, a bridge and buildings climbing the Coimbra hillside beneath a blue sky.", src: "/images/references/mondego-coimbra.jpg",
    author: "Leandro Neumann Ciuffo", sourceUrl: "https://commons.wikimedia.org/wiki/File:Coimbra_e_o_rio_Mondego_(6167200429).jpg",
    license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", capturedDate: "2011-09-20",
    sha256: "11fd35e5308a706ab533e84e249f3f51fd8f57d664858c0b3a836f43ee7e851d", width: 1280, height: 859,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
  { id: "garonne-toulouse", title: "Garonne · Toulouse", site: "Garonne River, Toulouse, France", role: "02 / Surface & structures",
    alt: "Panoramic river scene with a weir, exposed textured surfaces, reflections, bridges and buildings on the opposite bank.", src: "/images/references/garonne-toulouse.jpg",
    author: "Tiia Monto", sourceUrl: "https://commons.wikimedia.org/wiki/File:Toulouse_-_Garonne.jpg",
    license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", capturedDate: "2012-08-28",
    sha256: "34c11fa89a03c1aa0dbf43de16c1f2732a3e046c0055c869c96bad447eb794de", width: 1280, height: 481,
    derivative: "Wikimedia 1280px thumbnail; source photograph is panoramic. No project pixel edits. Display may crop to fit." },
  { id: "hoffselva-oslo", title: "Hoffselva · Oslo", site: "Hoffselva at Skøyen, Oslo, Norway", role: "03 / An urban stream",
    alt: "Narrow stream between vegetated banks, a modern building and a railing, running beneath a road bridge.", src: "/images/references/hoffselva-oslo.jpg",
    author: "Jan-Tore Egge", sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoffselva_ved_Sk%C3%B8yen_I.jpg",
    license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", capturedDate: "2014-05-12",
    sha256: "8d5217786fdf35351f94c8ba3e105225046766eeb50d75e4da93be770c573053", width: 1280, height: 960,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
  { id: "mondego-bridge", title: "Mondego · Bridges & green banks", site: "Mondego River, Coimbra, Portugal", role: "04 / River connections",
    alt: "Coimbra's river, pedestrian bridge, a road bridge, wooded banks and roofs in the foreground.", src: "/images/references/mondego-bridge.jpg",
    author: "Joseolgon", sourceUrl: "https://commons.wikimedia.org/wiki/File:Coimbra_2021_(11).jpg",
    license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", capturedDate: "2021-08-20",
    sha256: "672b46738dea3579bba8b8227e07eda036ebcac7ef11b5c9cab0e5978ed1bd63", width: 1280, height: 853,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
  { id: "mondego-riverbank", title: "Mondego · Parque Verde", site: "Mondego River, Coimbra, Portugal", role: "05 / Water & public space",
    alt: "A pedestrian footbridge, trees and people beside the Mondego; the source photographer's watermark is retained.", src: "/images/references/mondego-riverbank.jpg",
    author: "Vitor Oliveira", sourceUrl: "https://commons.wikimedia.org/wiki/File:Parque_Verde_do_Mondego_-_Coimbra_-_Portugal_(6970758957).jpg",
    license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", capturedDate: "2012-03-10",
    sha256: "7a6141fc6aa8bc9a4b7371d98b6779bba288a380ee79b2ab9fcf6e71f73a92b7", width: 1280, height: 1921,
    derivative: "Wikimedia 1280px thumbnail; original watermark retained. No project pixel edits. Display may crop to fit." },
  { id: "garonne-pont-neuf", title: "Garonne · Pont Neuf riverbank", site: "Garonne River, Toulouse, France", role: "06 / An engineered bank",
    alt: "Garonne water beside a grassy bank, red-brick wall, steps and trees, with Pont Neuf in the distance.", src: "/images/references/garonne-pont-neuf.jpg",
    author: "Phillip Maiwald (Nikopol)", sourceUrl: "https://commons.wikimedia.org/wiki/File:Toulouse_garonne_with_pont_neuf.jpg",
    license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0/", capturedDate: "2010-06-18",
    sha256: "30627519bc5c920b97ba7490331e6b4f26640a437a34896918adb6f4468d967c", width: 1280, height: 802,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
  { id: "garonne-promenade", title: "Garonne · Green promenade", site: "Garonne River, Toulouse, France", role: "07 / Vegetation & access",
    alt: "Garonne water bordered by dense green vegetation, a public path, lamps and urban buildings.", src: "/images/references/garonne-promenade.jpg",
    author: "Joachim Hocine", sourceUrl: "https://commons.wikimedia.org/wiki/File:Vue_sur_les_rives_d%E2%80%99Empalot_et_la_promenade_le_long_de_la_Garonne.jpg",
    license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", capturedDate: "2019-06-18",
    sha256: "aba0b073ccfd348ce5ce1f57dcf8b7e2220aa21772464184fe16149b0a542eaa", width: 1280, height: 852,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
  { id: "hoffselva-engebrets", title: "Hoffselva · Engebrets vei", site: "Hoffselva at Engebrets vei, Oslo, Norway", role: "08 / A closer stream view",
    alt: "A narrow stream with ripples, stone edges, leafy branches and moss, viewed from above.", src: "/images/references/hoffselva-engebrets.jpg",
    author: "Jan-Tore Egge", sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoffselva_ved_Engebrets_vei.jpg",
    license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", capturedDate: "2016-05-25",
    sha256: "a9de74b759c913603a0103fe8c1be32965d37ec7b11c95c6c5b9a2404b31f547", width: 1280, height: 1047,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
  { id: "hoffselva-nedre", title: "Hoffselva · Nedre Skøyen", site: "Hoffselva at Nedre Skøyen vei, Oslo, Norway", role: "09 / Stream & infrastructure",
    alt: "A shallow-looking stream with stones and overhanging trees, beside a timber retaining wall and visible pipes.", src: "/images/references/hoffselva-nedre.jpg",
    author: "Helge Høifødt", sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoffselva_ved_Nedre_Sk%C3%B8yen_vei_8.jpg",
    license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", capturedDate: "2020-04-26",
    sha256: "70e5d79751fe00348fedddbd13fa0d3675d72870f086fa697094c81d7751d0bf", width: 1280, height: 1043,
    derivative: "Wikimedia 1280px thumbnail; no project pixel edits. Display may crop to fit." },
] as const;
// Extended public archive: catalogue sources only, never fabricated citizen/AI records.
export const extendedReferencePhotos = [
  {
    "id": "mondego-archive-01",
    "title": "Açude-ponte de Coimbra, Rio Mondego 01",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Açude-ponte de Coimbra, Rio Mondego 01. Photographer-supplied date 2026-05-17.",
    "src": "/images/references/mondego-archive-01.jpg",
    "author": "GualdimG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A%C3%A7ude-ponte_de_Coimbra,_Rio_Mondego_01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2026-05-17",
    "sha256": "65c528338ccc8ee279cbcb2557452214a74776ec72522797521bad5714738490",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2026-05-17",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-02",
    "title": "Coimbra, Vista do Rio Mondego desde a Couraça de Lisboa 01",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Coimbra, Vista do Rio Mondego desde a Couraça de Lisboa 01. Photographer-supplied date 2023-08-28.",
    "src": "/images/references/mondego-archive-02.jpg",
    "author": "GualdimG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coimbra,_Vista_do_Rio_Mondego_desde_a_Coura%C3%A7a_de_Lisboa_01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2023-08-28",
    "sha256": "49e2499b4daf8724ca335b047776f45a01ac65fa5844947adfc0cebf3ffed651",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2023-08-28 12:22:30",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-03",
    "title": "Coimbra-MondegoPanorama",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Coimbra-MondegoPanorama. Photographer-supplied date 2007-10-10.",
    "src": "/images/references/mondego-archive-03.jpg",
    "author": "António Pinto",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coimbra-MondegoPanorama.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "capturedDate": "2007-10-10",
    "sha256": "3e58c887cb2ea1ea64190d90ac9892906f4a4dbe2885c0974683e6eaf9d27e5c",
    "width": 960,
    "height": 701,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2007-10-10 13:50",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-04",
    "title": "Coimbra & Mondego (4054792985)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Coimbra & Mondego (4054792985). Photographer-supplied date 2009-10-02.",
    "src": "/images/references/mondego-archive-04.jpg",
    "author": "Antero Pires from Corroios, Portugal",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coimbra_%26_Mondego_(4054792985).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2009-10-02",
    "sha256": "521285d7152e95e62cf43e6e8731b556cf95bf969b0cfc1a671d7c14763513f3",
    "width": 960,
    "height": 504,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2009-10-02 18:29",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-05",
    "title": "Coimbra Rio Mondego 4861",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Coimbra Rio Mondego 4861. Photographer-supplied date 2016-04-17.",
    "src": "/images/references/mondego-archive-05.jpg",
    "author": "GFreihalter",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coimbra_Rio_Mondego_4861.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "capturedDate": "2016-04-17",
    "sha256": "202afd3957795a9095fd83acf18e4a6ddae7e78ae108af9a4c1ca883cbaaa234",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2016-04-17",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-06",
    "title": "Rio Mondego em Coimbra 01",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego em Coimbra 01. Photographer-supplied date 2012-06-11.",
    "src": "/images/references/mondego-archive-06.jpg",
    "author": "GualdimG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_em_Coimbra_01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2012-06-11",
    "sha256": "bacbef6fe806cdb81ae5df32cc68bb169cf16f9247b48a01bafae4e74ee0f6b9",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2012-06-11 12:41:49",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-07",
    "title": "Parque Verde do Mondego - Coimbra - Portugal (8261478687)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Parque Verde do Mondego - Coimbra - Portugal (8261478687). Photographer-supplied date 2012-12-10.",
    "src": "/images/references/mondego-archive-07.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parque_Verde_do_Mondego_-_Coimbra_-_Portugal_(8261478687).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2012-12-10",
    "sha256": "5b09c60cda8a3380fe1a554dd5b69b39686292cb4f8d1a895d62134e3bacbf74",
    "width": 960,
    "height": 619,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2012-12-10 18:34",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-08",
    "title": "Rio Mondego, Coimbra, Portugal (54878966910)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego, Coimbra, Portugal (54878966910). Photographer-supplied date 2025-08-01.",
    "src": "/images/references/mondego-archive-08.jpg",
    "author": "Pom' from France, European Union",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego,_Coimbra,_Portugal_(54878966910).jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2025-08-01",
    "sha256": "7071f1467538c7b3c82291e111d099c86684a25e2163972d50629ec2216709ff",
    "width": 960,
    "height": 960,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2025-08-01 14:54",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-09",
    "title": "Rio Mondego - Coimbra - Portugal (20524115904)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego - Coimbra - Portugal (20524115904). Photographer-supplied date 2015-09-04.",
    "src": "/images/references/mondego-archive-09.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_-_Coimbra_-_Portugal_(20524115904).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2015-09-04",
    "sha256": "2877d12930d4e9f33dfc77e94691c57fc322e77a051403d55bbc4d35bafc53b6",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2015-09-04 22:17",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-10",
    "title": "Rio Mondego - Coimbra - Portugal (22129394411)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego - Coimbra - Portugal (22129394411). Photographer-supplied date 2008-01-02.",
    "src": "/images/references/mondego-archive-10.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_-_Coimbra_-_Portugal_(22129394411).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2008-01-02",
    "sha256": "5afde1024f6becdffaf379006a3c2223a11ded7cb1b3c7c8ce89ea095a43fb22",
    "width": 960,
    "height": 674,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2008-01-02 23:40",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-11",
    "title": "Rio Mondego - Coimbra - Portugal (27464255673)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego - Coimbra - Portugal (27464255673). Photographer-supplied date 2008-07-13.",
    "src": "/images/references/mondego-archive-11.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_-_Coimbra_-_Portugal_(27464255673).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2008-07-13",
    "sha256": "e47d0134d358d3a95116db178fcce96e62fdca3a480690cd2fadddf53ef2a513",
    "width": 960,
    "height": 714,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2008-07-13 23:55",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-12",
    "title": "Rio Mondego - Coimbra - Portugal (7421792972)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego - Coimbra - Portugal (7421792972). Photographer-supplied date 2012-06-22.",
    "src": "/images/references/mondego-archive-12.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_-_Coimbra_-_Portugal_(7421792972).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2012-06-22",
    "sha256": "4bb58ae1660edd76b7d537018d89f44376d8db4a98187ce5e9483c97fd505688",
    "width": 960,
    "height": 1440,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2012-06-22 20:39",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-13",
    "title": "Rio Mondego - Coimbra - Portugal (8569409683)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego - Coimbra - Portugal (8569409683). Photographer-supplied date 2013-03-18.",
    "src": "/images/references/mondego-archive-13.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_-_Coimbra_-_Portugal_(8569409683).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2013-03-18",
    "sha256": "74e355233dcfd3c3f5f9efc228ef5a97a6c34b768e7764ee33e0301fc428acc1",
    "width": 960,
    "height": 483,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2013-03-18 23:02",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-14",
    "title": "Rio Mondego - Coimbra - Portugal (92504291)",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Rio Mondego - Coimbra - Portugal (92504291). Photographer-supplied date 2005-11-06.",
    "src": "/images/references/mondego-archive-14.jpg",
    "author": "Vitor Oliveira from Torres Vedras, PORTUGAL",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rio_Mondego_-_Coimbra_-_Portugal_(92504291).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "capturedDate": "2005-11-06",
    "sha256": "aa766729cd9ef3182ddf3d3c0c26f224e01f973c342df4d83fae9087a4130a4f",
    "width": 960,
    "height": 719,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2005-11-06 16:38",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "mondego-archive-15",
    "title": "Vista do Rio Mondego em Coimbra desde a ponte proveniente de Santa Clara",
    "site": "Mondego River, Coimbra, Portugal",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Vista do Rio Mondego em Coimbra desde a ponte proveniente de Santa Clara. Photographer-supplied date 2013-12-31.",
    "src": "/images/references/mondego-archive-15.jpg",
    "author": "Gato Preto",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vista_do_Rio_Mondego_em_Coimbra_desde_a_ponte_proveniente_de_Santa_Clara.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2013-12-31",
    "sha256": "ab818e2a9368646567b3f4f6d22272c5d2cffb5b00f4ce73882c498d634a7f48",
    "width": 960,
    "height": 1280,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "coimbra",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2013-12-31 17:26:09",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-01",
    "title": "Toulouse - Garonne Skyline at Sunset - 2012-02-22",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Toulouse - Garonne Skyline at Sunset - 2012-02-22. Photographer-supplied date 2012-02-22.",
    "src": "/images/references/garonne-archive-01.jpg",
    "author": "PierreSelim",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Toulouse_-_Garonne_Skyline_at_Sunset_-_2012-02-22.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "capturedDate": "2012-02-22",
    "sha256": "1155e53d750e141a6e9aec77453077bec891eb4391b94184d853a8b67ee20f1a",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2012-02-22",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-02",
    "title": "Toulouse - Garonne et Pont Neuf",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Toulouse - Garonne et Pont Neuf. Photographer-supplied date 2018-08-15.",
    "src": "/images/references/garonne-archive-02.jpg",
    "author": "Frédéric Neupont",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Toulouse_-_Garonne_et_Pont_Neuf.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2018-08-15",
    "sha256": "24e508bee36d7d4602932c0a7a15afe12a7dd449f68e9a719aaa2a3456547bef",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2018-08-15 10:15:53",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-03",
    "title": "Toulouse - Garonne quais et Pont-Neuf",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Toulouse - Garonne quais et Pont-Neuf. Photographer-supplied date 2021-08-20.",
    "src": "/images/references/garonne-archive-03.jpg",
    "author": "Frédéric Neupont",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Toulouse_-_Garonne_quais_et_Pont-Neuf.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2021-08-20",
    "sha256": "05bede73410c49b7e4cd3e3757f4d38be54543e7063c3a916849084641de5561",
    "width": 960,
    "height": 480,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2021-08-20 19:00:59",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-04",
    "title": "Toulouse Garonne panorama",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Toulouse Garonne panorama. Photographer-supplied date 2020-06-22.",
    "src": "/images/references/garonne-archive-04.jpg",
    "author": "Don-vip",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Toulouse_Garonne_panorama.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2020-06-22",
    "sha256": "da35cc40ec9f90b0a54c24d7f341d36e19c41bcb973c83e1c77e39c40b752d9c",
    "width": 960,
    "height": 358,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2020-06-22 16:52:36",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-05",
    "title": "Garonne, Toulouse, Midi-Pyrénées, France - panoramio (4)",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Garonne, Toulouse, Midi-Pyrénées, France - panoramio (4). Photographer-supplied date 2013-05-24.",
    "src": "/images/references/garonne-archive-05.jpg",
    "author": "M.Strīķis",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garonne,_Toulouse,_Midi-Pyr%C3%A9n%C3%A9es,_France_-_panoramio_(4).jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "capturedDate": "2013-05-24",
    "sha256": "83b5e8f14ae4e63fe5bc339700cbe1b6916347a2428dfb592f6a3163f4bde78b",
    "width": 960,
    "height": 638,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "Taken on 24 May 2013",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-06",
    "title": "Garonne - Toulouse - janvier 2023 01",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Garonne - Toulouse - janvier 2023 01. Photographer-supplied date 2023-01-19.",
    "src": "/images/references/garonne-archive-06.jpg",
    "author": "Duch",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garonne_-_Toulouse_-_janvier_2023_01.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "capturedDate": "2023-01-19",
    "sha256": "f25f24f352cd247f25d30843c171597186d268a373457de30f2adb547218a92d",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2023-01-19 11:48:23",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-07",
    "title": "Garonne à Toulouse - Bazacle",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Garonne à Toulouse - Bazacle. Photographer-supplied date 2020-06-22.",
    "src": "/images/references/garonne-archive-07.jpg",
    "author": "Don-vip",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garonne_%C3%A0_Toulouse_-_Bazacle.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2020-06-22",
    "sha256": "c0470b9eea86c4a61bd4e9619b94fd828fdff28e8b5f7ce4674c3072fcc94e92",
    "width": 960,
    "height": 524,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2020-06-22 17:47:57",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-08",
    "title": "La Garonne à Toulouse 13",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: La Garonne à Toulouse 13. Photographer-supplied date 2023-09-07.",
    "src": "/images/references/garonne-archive-08.jpg",
    "author": "FrDr",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:La_Garonne_%C3%A0_Toulouse_13.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2023-09-07",
    "sha256": "ec3d14ba1cacbc7fde205bec36967a9570e01e86275ad7a9884709daccd94f72",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2023-09-07 09:55:24",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-09",
    "title": "Quai Saint-Pierre et Garonne (Toulouse)",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Quai Saint-Pierre et Garonne (Toulouse). Photographer-supplied date 2019-09-29.",
    "src": "/images/references/garonne-archive-09.jpg",
    "author": "Abdoucondorcet",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quai_Saint-Pierre_et_Garonne_(Toulouse).jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2019-09-29",
    "sha256": "227d461afe153dba99ea42ab493c2005fff0472a09f6ec40da8f7763b762aa71",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2019-09-29 12:14:16",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-10",
    "title": "Quais de Garonne à Toulouse",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Quais de Garonne à Toulouse. Photographer-supplied date 2013-08-15.",
    "src": "/images/references/garonne-archive-10.jpg",
    "author": "Frédéric Neupont",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quais_de_Garonne_%C3%A0_Toulouse.jpg",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "capturedDate": "2013-08-15",
    "sha256": "30a2495d91ebf4e92fb94b51fc1898caa4a59e2afea1d56793d58519dfce95b8",
    "width": 960,
    "height": 640,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2013-08-15 19:34:23",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-11",
    "title": "(Toulouse) L’écluse Saint-Michel sur la Garonne vue du pont Saint-Michel",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: (Toulouse) L’écluse Saint-Michel sur la Garonne vue du pont Saint-Michel. Photographer-supplied date 2022-12-21.",
    "src": "/images/references/garonne-archive-11.jpg",
    "author": "Didier Descouens",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(Toulouse)_L%27%C3%A9cluse_Saint-Michel_sur_la_Garonne_vue_du_pont_Saint-Michel.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2022-12-21",
    "sha256": "db6835bd52f95b86e4fe14cc8702571f2c56282112a6fd5e2b93c76106af7184",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "Taken on 21 December 2022",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-12",
    "title": "Ferris wheel on the bank of Garonne river in Toulouse, France",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Ferris wheel on the bank of Garonne river in Toulouse, France. Photographer-supplied date 2024-07-15.",
    "src": "/images/references/garonne-archive-12.jpg",
    "author": "Shishirdasika",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ferris_wheel_on_the_bank_of_Garonne_river_in_Toulouse,_France.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2024-07-15",
    "sha256": "7b5222c726571fc21ae70996bdef48e0d7a587e769f21b5a07956df6c7fb1c13",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "15 July 2024 (according to Exif data)",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-13",
    "title": "Garonne - Toulouse - janvier 2023 02",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Garonne - Toulouse - janvier 2023 02. Photographer-supplied date 2023-01-19.",
    "src": "/images/references/garonne-archive-13.jpg",
    "author": "Duch",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garonne_-_Toulouse_-_janvier_2023_02.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "capturedDate": "2023-01-19",
    "sha256": "c55b6c069554e1142b8baf72ea97454089e147a651248b062c740583296c4ec5",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2023-01-19 11:49:42",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "garonne-archive-14",
    "title": "De la grave hospital on the banks of Garonne river in Toulouse, France",
    "site": "Garonne River, Toulouse, France",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: De la grave hospital on the banks of Garonne river in Toulouse, France. Photographer-supplied date 2024-07-15.",
    "src": "/images/references/garonne-archive-14.jpg",
    "author": "Shishirdasika",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:De_la_grave_hospital_on_the_banks_of_Garonne_river_in_Toulouse,_France.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2024-07-15",
    "sha256": "e4ae633ed48ba9d3eba2d49d4477ab5e71b99a65e0ad2e971f71e3b6c9234fa8",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "toulouse",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "15 July 2024 (according to Exif data)",
    "checkedAt": "2026-10-03"
  },
  {
    "id": "hoffselva-archive-01",
    "title": "Hoffselva ved Skøyen II",
    "site": "Hoffselva at Skøyen, Oslo, Norway",
    "role": "Historical photo archive",
    "alt": "Historical source photograph: Hoffselva ved Skøyen II. Photographer-supplied date 2014-05-12.",
    "src": "/images/references/hoffselva-archive-01.jpg",
    "author": "Jan-Tore Egge",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hoffselva_ved_Sk%C3%B8yen_II.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "capturedDate": "2014-05-12",
    "sha256": "61ad61f4710970e32995f3dda87eed79f049cb45b6fc5dc75147eed64d9ac35a",
    "width": 960,
    "height": 720,
    "derivative": "Wikimedia 960px thumbnail; no project pixel edits. Full frame available; display may crop.",
    "cityId": "oslo",
    "dateSource": "Commons DateTimeOriginal; day precision retained; camera clock not independently verified",
    "sourceDateRaw": "2014-05-12 16:06:43",
    "checkedAt": "2026-10-03"
  }
] as const;
export const europeanPhotoLibrary = [...referencePhotos, ...extendedReferencePhotos];
export const allReferencePhotos = [...europeanPhotoLibrary, ...archivedReferencePhotos];
export type ReferencePhoto = (typeof allReferencePhotos)[number];
// Curated viewing labels; canonical source titles/credits/receipt metadata stay unchanged.
const archiveViewingTitles: Record<string, string> = {
  "mondego-archive-01": "Mondego · Coimbra weir bridge", "mondego-archive-02": "Mondego · From Couraça de Lisboa",
  "mondego-archive-03": "Mondego · Coimbra panorama", "mondego-archive-04": "Mondego · Evening reflections",
  "mondego-archive-05": "Mondego · City and river", "mondego-archive-06": "Mondego · Open river panorama",
  "mondego-archive-07": "Mondego · Parque Verde footbridge", "mondego-archive-08": "Mondego · Looking across Coimbra",
  "mondego-archive-09": "Mondego · Water and wooded banks", "mondego-archive-10": "Mondego · Urban riverbank",
  "mondego-archive-11": "Mondego · Green banks and reflections", "mondego-archive-12": "Mondego · Riverboat and footbridge",
  "mondego-archive-13": "Mondego · Beneath open sky", "mondego-archive-14": "Mondego · Open river view",
  "mondego-archive-15": "Mondego · From Santa Clara bridge", "garonne-archive-01": "Garonne · Toulouse at sunset",
  "garonne-archive-02": "Garonne · Pont Neuf beneath the trees", "garonne-archive-03": "Garonne · Toulouse quays and Pont Neuf",
  "garonne-archive-04": "Garonne · Toulouse panorama", "garonne-archive-05": "Garonne · River and wooded bank",
  "garonne-archive-06": "Garonne · January river view", "garonne-archive-07": "Garonne · Bazacle",
  "garonne-archive-08": "Garonne · Brick quays", "garonne-archive-09": "Garonne · Quai Saint-Pierre",
  "garonne-archive-10": "Garonne · Trees beside the quays", "garonne-archive-11": "Garonne · Saint-Michel lock",
  "garonne-archive-12": "Garonne · Toulouse riverside", "garonne-archive-13": "Garonne · January banks",
  "garonne-archive-14": "Garonne · La Grave riverside", "hoffselva-archive-01": "Hoffselva · Skøyen stream corridor",
};
export function photoViewingTitle(photo: { id: string; title: string }) { return archiveViewingTitles[photo.id] || photo.title; }
export function referenceDimensions(photo: ReferencePhoto) {
  return "width" in photo ? { width: photo.width, height: photo.height } : { width: 1280, height: photo.id === "scenic-reflection" ? 853 : 960 };
}

const evidenceDateSchema = z.string().date();
const recordedTimestampSchema = z.string().datetime({ offset: true });
const localTimestampSchema = z.string().datetime({ local: true });
const recordedTimestampFormat = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2})$/;
const localTimestampFormat = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?$/;
export type EvidenceTimePrecision = "date_only" | "timestamp" | "zone_unknown" | "missing" | "invalid";

/** Require an actual ISO calendar/clock and supplied zone; Date.parse alone normalizes impossible days. */
export function validRecordedTimestamp(value: string) {
  return recordedTimestampFormat.test(value) && recordedTimestampSchema.safeParse(value).success
    && Number.isFinite(Date.parse(value));
}
export function evidenceTimePrecision(value: string): EvidenceTimePrecision {
  if (!value.trim()) return "missing";
  if (evidenceDateSchema.safeParse(value).success) return "date_only";
  if (validRecordedTimestamp(value)) return "timestamp";
  if (localTimestampFormat.test(value) && localTimestampSchema.safeParse(value).success) return "zone_unknown";
  return "invalid";
}

// Source dates have day precision. Unknown zones and invalid inputs never acquire a device-local instant.
export function displayEvidenceTime(value: string) {
  const precision = evidenceTimePrecision(value);
  if (precision === "date_only")
    return new Date(`${value}T12:00:00Z`).toLocaleDateString("en-GB", { dateStyle: "medium", timeZone: "UTC" }) + " · date only";
  if (precision === "zone_unknown") return `${value.replace("T", " ")} · time zone unknown`;
  if (precision === "invalid") return "Time not available · invalid date or time";
  return precision === "timestamp"
    ? new Date(value).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) + " UTC"
    : "Time not available";
}
